### ISSUE TITLE
Notifications are not displayed

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#371]
Seen on production platform :

```
| DEBUG| 09:58:03.072 | org.oasis_eu.portal.core.model.catalog.ApplicationInstance - Discarding unknown property destruction_uri
| DEBUG| 09:58:03.072 | org.oasis_eu.portal.core.model.catalog.ApplicationInstance - Discarding unknown property created
| DEBUG| 09:58:03.072 | org.oasis_eu.portal.core.model.catalog.ApplicationInstance - Discarding unknown property modified
| ERROR| 09:58:03.095 | org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.oasis_eu.portal.services.PortalNotificationService.lambda$getNotifications$47(PortalNotificationService.java:101) ~[ozwillo-portal-front-1.40.jar!/:na]
	at org.oasis_eu.portal.services.PortalNotificationService$$Lambda$192/827531040.apply(Unknown Source) ~[na:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_20]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_20]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[na:1.8.0_20]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[na:1.8.0_20]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_20]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_20]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_20]
	at org.oasis_eu.portal.services.PortalNotificationService.getNotifications(PortalNotificationService.java:108) ~[ozwillo-portal-front-1.40.jar!/:na]
	at org.oasis_eu.portal.services.PortalNotificationService.getNotifications(PortalNotificationService.java:233) ~[ozwillo-portal-front-1.40.jar!/:na]
	at org.oasis_eu.portal.front.my.notifications.NotificationsAJAXServices.getNotifications(NotificationsAJAXServices.java:42) ~[ozwillo-portal-front-1.40.jar!/:na]
```

**Comment by bobeal** [comment]
Caused by a notification on an instance for which the associated application no longer exists (Ozmarue something).

**Comment by tbroyer** [comment]
Actually, the application mist likely still exists but has been switched to `visible: false` to hide it from the catalog.

**Comment by bobeal** [comment]
Yes, my bad, I was not looking in the right collection.
